name: Generate Stats

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: generate stats.svg
        uses: anuraghazra/github-readme-stats@master
        with:
          username: ${{ github.repository_owner }}

      - name: push stats.svg to stats-output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: stats-output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
